using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyGame
{
    public class LevelController
    {
        private static Stopwatch stopwatch = new Stopwatch();
        private List<Arrows> arrowList = new List<Arrows>();
        private Image background1 = Engine.LoadImage("assets/Background.jpg");
        private Image background2 = Engine.LoadImage("assets/Background2.jpg");
        private Player player1;
        private GetReadySign getReadySign;
        private int endLevel1Time = 228;
        private int endLevel2Time = 216;
        private int gamePointsToWin1 = 2832;
        private int gamePointsToWin2 = 2770;
        private int initialPlayerPosition = 300;
        private ArrowsFactory arrowsFactory = new ArrowsFactory();
        private HUD hud = new HUD();
        private TriggerArrowAnimation triggerArrowAnimation = new TriggerArrowAnimation();
        private int level;


        public List<Arrows> ArrowList => arrowList;
        public Stopwatch Stopwatch => stopwatch;
        public Player Player1 => player1;
        public TriggerArrowAnimation TriggerArrowAnimation => triggerArrowAnimation;

        public void InitializeLevel(int level)
        {
            this.level = level;
            if (level == 1)
            {
                arrowList.Add(ArrowsFactory.CreateArrows(ArrowType.rightArrowS, 0f));
                arrowList.Add(ArrowsFactory.CreateArrows(ArrowType.upArrowS, 0f));
                arrowList.Add(ArrowsFactory.CreateArrows(ArrowType.downArrowS, 0f));
                arrowList.Add(ArrowsFactory.CreateArrows(ArrowType.leftArrowS, 0f));
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 12.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 13.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 13.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 13.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 13.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 14.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 14.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 14.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 14.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 15.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 15.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 15.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 15.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 16.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 16.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 16.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 17.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 17.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 17.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 18.02f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 18.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 18.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 18.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 19.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 19.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 19.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 20.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 20.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 20.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 21.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 21.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 21.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 21.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 22.21f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 22.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 22.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 23.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 23.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 23.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 23.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 24.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 24.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 24.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 25.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 25.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 25.95f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 26.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 26.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 26.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 27.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 27.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 27.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 28.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 28.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 28.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 28.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 29.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 29.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 30.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 30.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 30.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 30.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 31.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 31.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 31.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 32.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 32.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 32.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 33.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 33.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 33.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 34.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 34.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 34.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 34.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 35.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 35.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 35.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 36.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 36.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 36.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 37.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 37.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 37.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 40.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 42.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 43.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 43.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 43.73f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 44.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 44.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 44.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 44.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 45.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 45.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 45.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 46.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 46.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 46.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 47.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 47.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 47.60f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 47.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 48.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 48.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 48.73f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 48.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 49.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 49.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 49.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 50.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 50.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 51.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 51.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 51.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 51.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 52.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 52.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 52.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 53.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 53.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 53.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 53.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 54.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 54.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 54.88f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 55.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 55.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 55.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 56.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 56.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 56.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 57.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 57.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 57.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 57.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 58.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 58.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 58.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 59.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 59.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 59.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 59.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 60.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 60.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 60.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 61.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 61.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 62.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 62.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 63.02f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 63.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 64.02f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 64.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 64.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 64.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 65.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 65.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 65.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 66.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 66.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 66.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 67.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 67.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 67.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 70.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 72.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 72.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 73.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 73.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 73.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 73.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 74.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 74.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 75.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 76.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 77.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 77.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 78.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 78.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 78.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 79.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 79.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 79.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 80.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 80.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 81.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 81.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 82.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 82.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 82.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 83.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 83.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 83.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 83.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 84.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 85.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 86.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 87.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 87.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 88.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 88.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 88.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 89.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 89.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 89.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 89.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 90.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 90.95f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 91.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 91.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 92.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 92.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 93.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 94.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 94.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 105.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 105.60f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 105.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 106.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 106.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 106.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 107.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 107.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 107.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 108.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 108.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 108.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 109.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 109.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 109.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 110.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 110.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 111.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 111.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 111.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 112.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 112.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 112.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 113.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 113.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 113.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 113.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 114.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 114.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 115.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 115.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 115.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 116.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 116.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 116.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 117.02f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 117.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 117.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 118.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 118.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 118.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 119.02f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 119.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 119.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 120.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 120.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 120.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 121.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 121.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 121.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 122.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 122.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 122.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 123.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 123.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 123.73f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 124.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 124.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 124.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 125.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 125.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 125.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 126.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 126.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 126.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 127.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 127.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 127.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 128.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 128.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 128.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 129.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 129.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 129.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 129.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 130.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 132.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 135.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 135.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 135.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 135.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 136.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 136.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 136.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 137.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 137.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 138.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 140.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 140.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 140.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 140.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 141.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 141.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 141.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 142.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 143.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 143.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 143.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 144.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 145.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 145.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 145.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 145.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 146.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 146.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 146.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 147.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 147.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 148.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 149.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 150.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 150.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 150.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 151.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 151.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 151.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 152.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 152.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 153.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 153.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 153.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 154.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 154.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 155.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 155.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 156.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 157.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 158.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 158.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 158.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 158.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 159.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 159.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 160.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 160.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 160.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 160.73f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 160.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 161.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 161.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 161.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 162.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 162.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 162.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 163.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 163.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 163.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 163.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 164.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 164.60f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 164.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 165.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 165.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 165.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 166.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 166.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 166.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 167.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 167.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 167.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 168.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 168.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 168.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 169.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 169.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 169.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 169.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 170.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 170.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 170.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 171.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 171.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 171.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 171.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 172.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 172.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 172.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 173.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 173.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 173.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 173.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 174.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 174.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 174.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 175.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 175.60f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 175.88f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 176.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 176.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 176.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 177.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 177.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 177.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 178.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 178.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 179.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 180.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 180.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 181.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 182.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 182.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 185.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 187.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 187.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 187.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 188.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 188.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 188.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 189.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 189.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 189.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 189.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 191.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 192.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 192.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 192.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 193.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 193.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 193.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 194.21f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 194.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 195.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 195.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 196.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 196.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 197.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 197.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 197.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 197.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 198.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 198.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 198.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 199.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 199.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 199.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 200.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 201.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 202.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 202.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 203.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 203.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 203.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 203.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 204.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 204.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 204.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 205.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 205.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 206.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 206.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 207.02f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 207.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 208.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 208.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 209.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 210.55f);

                player1 = new Player(initialPlayerPosition, initialPlayerPosition);
                getReadySign = new GetReadySign();
                stopwatch.Start();
            }
            if (level == 2)
            {
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 6.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 6.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 15.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 16.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 16.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 16.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 16.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 17.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 17.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 17.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 17.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 17.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 18.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 18.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 18.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 19.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 19.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 19.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 19.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 20.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 20.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 20.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 21.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 21.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 21.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 21.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 22.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 22.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 23.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 23.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 23.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 23.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 24.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 24.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 25.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 25.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 25.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 26.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 26.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 26.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 27.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 27.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 27.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 27.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 28.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 28.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 28.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 29.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 29.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 29.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 30.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 30.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 30.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 30.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 31.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 31.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 31.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 32.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 32.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 32.88f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 33.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 33.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 33.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 34.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 34.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 34.95f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 35.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 35.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 35.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 36.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 36.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 36.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 37.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 37.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 37.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 37.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 38.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 38.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 38.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 39.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 39.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 39.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 40.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 40.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 40.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 41.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 41.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 41.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 42.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 42.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 42.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 44.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 44.73f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 45.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 45.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 46.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 47.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 47.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 47.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 49.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 49.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 49.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 50.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 50.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 51.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 51.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 51.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 51.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 51.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 52.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 52.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 52.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 53.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 53.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 53.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 53.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 54.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 54.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 55.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 56.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 56.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 56.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 57.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 58.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 58.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 59.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 59.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 60.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 60.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 60.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 60.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 61.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 61.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 61.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 61.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 62.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 62.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 62.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 63.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 63.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 63.95f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 64.21f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 64.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 64.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 65.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 65.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 65.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 65.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 66.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 66.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 66.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 66.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 67.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 67.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 67.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 68.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 68.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 68.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 69.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 69.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 69.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 70.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 70.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 70.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 70.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 71.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 71.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 71.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 71.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 72.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 72.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 73.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 73.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 73.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 73.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 74.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 74.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 74.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 75.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 75.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 75.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 76.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 76.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 76.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 77.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 77.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 77.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 78.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 78.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 78.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 78.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 79.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 79.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 79.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 80.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 80.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 80.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 81.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 81.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 86.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 86.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 86.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 87.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 87.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 87.60f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 87.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 88.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 88.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 88.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 88.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 89.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 89.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 89.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 90.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 90.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 90.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 90.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 91.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 91.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 91.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 91.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 92.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 92.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 92.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 93.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 93.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 94.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 94.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 94.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 94.88f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 95.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 95.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 96.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 96.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 96.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 97.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 97.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 97.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 97.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 98.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 98.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 98.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 99.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 99.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 99.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 100.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 100.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 100.60f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 101.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 101.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 101.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 101.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 102.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 102.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 103.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 103.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 103.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 103.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 104.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 104.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 105.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 105.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 105.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 106.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 106.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 106.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 106.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 107.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 107.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 107.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 108.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 108.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 108.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 108.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 109.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 109.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 109.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 110.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 110.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 110.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 110.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 111.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 111.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 112.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 112.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 112.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 113.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 113.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 114.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 115.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 115.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 115.88f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 116.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 117.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 117.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 118.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 118.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 119.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 119.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 120.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 120.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 121.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 121.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 121.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 122.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 122.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 122.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 122.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 123.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 123.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 123.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 124.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 124.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 124.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 125.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 125.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 126.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 127.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 127.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 127.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 129.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 129.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 129.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 130.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 130.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 131.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 131.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 131.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 131.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 132.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 132.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 132.73f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 132.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 133.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 133.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 152.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 153.02f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 153.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 153.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 153.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 154.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 154.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 154.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 154.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 155.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 155.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 155.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 155.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 156.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 156.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 156.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 156.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 157.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 157.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 157.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 157.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 158.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 158.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 158.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 158.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 159.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 159.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 159.95f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 160.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 160.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 160.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 161.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 161.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 161.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 162.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 162.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 162.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 163.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 163.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 163.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 163.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 164.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 164.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 164.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 165.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 165.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 165.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 166.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 166.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 167.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 167.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 167.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 167.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 168.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 168.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 169.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 169.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 169.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 169.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 170.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 170.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 170.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 173.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 174.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 174.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 174.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 176.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 176.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 176.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 177.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 178.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 178.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 179.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 179.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 180.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 180.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 180.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 180.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 181.21f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 181.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 181.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 181.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 182.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 182.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 182.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 182.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 183.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 183.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 184.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 184.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 185.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 185.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 186.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 186.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 187.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 188.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 188.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 189.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 189.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 189.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 190.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 190.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 190.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 190.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 191.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 191.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 191.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 191.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 192.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 192.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 194.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 199.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 199.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 199.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 199.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 200.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 200.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 200.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 201.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 201.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 201.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 201.88f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 204.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 205.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 206.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 207.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 208.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 209.79f);
                stopwatch.Start();
            }
        }

        public void EndLevel()
        {
            if (level == 1)
            {
                if (stopwatch.Elapsed.TotalSeconds >= endLevel1Time)
                {
                    stopwatch.Restart();
                    stopwatch.Stop();

                    if (GameManager.Instance.Points.RythmPoints >= gamePointsToWin1)
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.nextLevel);
                    }
                    else
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.lose);
                    }
                }
            }
            if (level == 1)
            {
                if (stopwatch.Elapsed.TotalSeconds >= endLevel1Time)
                {
                    stopwatch.Restart();
                    stopwatch.Stop();

                    if (GameManager.Instance.Points.RythmPoints >= gamePointsToWin1)
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.win);
                    }
                    else
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.lose);
                    }
                }
            }
            if (level == 2)
            {
                if (stopwatch.Elapsed.TotalSeconds >= endLevel2Time)
                {
                    stopwatch.Restart();
                    stopwatch.Stop();

                    if (GameManager.Instance.Points.RythmPoints >= gamePointsToWin2)
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.win);
                    }
                    else
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.lose);
                    }
                }
            }
        }

        public enum ArrowDirection
        {
            Left,
            Right,
            Up,
            Down
        }

        public void Update()
        {
            player1.Update();
            getReadySign.Update();
            arrowsFactory.Update();

            for (int i = 0; i < arrowList.Count; i++)
            {
                arrowList[i].Update();
            }

            EndLevel();
        }
        public void Render()
        {
            Engine.Clear();
            if (level == 1)
            {
                Engine.Draw(background1, 0, 0);
            }
            if (level == 2)
            {
                Engine.Draw(background2, 0, 0);
            }
            player1.Render();
            getReadySign.Render();
            hud.Render();

            for (int i = 0; i < arrowList.Count; i++)
            {
                arrowList[i].Render();
            }

            Engine.Show();
        }
    }
}
