using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyGame
{
    public class LevelController
    {
        private static Stopwatch stopwatch = new Stopwatch();
        private List<Arrows> arrowList = new List<Arrows>();
        private Image background = Engine.LoadImage("assets/Background.jpg");
        private Player player1;
        private int leftArrowPos = 628;
        private int downArrowPos = 728;
        private int upArrowPos = 828;
        private int rightArrowPos = 928;
        private int arrowsYPos = 20;
        private int endLevelTime = 228;
        private int gamePointsToWin = 3050;
        private int initialPlayerPosition = 300;

        public List<Arrows> ArrowList => arrowList;
        public Stopwatch Stopwatch => stopwatch;
        public Player Player1 => player1;

        //public delegate void OnLevelEnd();
        //public event OnLevelEnd onLevelEnd;



        public void InitializeLevel()
        {
            arrowList.Add(new Arrows(rightArrowPos, arrowsYPos, true, 0));
            arrowList.Add(new Arrows(upArrowPos, arrowsYPos, true, 0));
            arrowList.Add(new Arrows(downArrowPos, arrowsYPos, true, 0));
            arrowList.Add(new Arrows(leftArrowPos, arrowsYPos, true, 0));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 16.48f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 16.72f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 17.05f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 17.31f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 17.62f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 17.89f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 18.24f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 18.69f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 18.98f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 19.26f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 19.53f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 19.87f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 20.09f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 20.48f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 20.87f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 21.13f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 21.55f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 21.80f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 22.15f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 22.56f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 23.02f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 23.33f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 23.66f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 24.07f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 24.36f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 24.61f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 24.91f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 25.20f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 25.58f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 25.90f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 26.16f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 26.68f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 26.92f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 27.40f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 27.73f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 28.13f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 28.39f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 28.65f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 29.15f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 29.43f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 29.68f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 29.98f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 30.24f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 30.56f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 30.88f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 31.18f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 31.68f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 32.01f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 32.26f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 32.51f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 32.72f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 33.10f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 33.40f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 33.72f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 34.06f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 34.31f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 34.64f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 34.98f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 35.31f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 35.65f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 36.04f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 36.26f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 36.68f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 37.08f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 37.73f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 38.31f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 38.90f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 39.49f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 40.11f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 40.79f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 41.46f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 44.03f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 46.53f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 46.81f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 47.08f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 47.35f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 47.63f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 47.96f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 48.33f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 48.67f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 49.03f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 49.31f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 49.66f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 49.91f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 50.27f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 50.54f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 50.83f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 51.17f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 51.53f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 51.80f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 52.05f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 52.34f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 52.68f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 53.09f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 53.33f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 53.70f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 54.06f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 54.37f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 54.74f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 54.98f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 55.29f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 55.56f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 55.85f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 56.18f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 56.53f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 56.92f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 57.22f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 57.50f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 57.77f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 58.10f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 58.39f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 58.69f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 59.01f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 59.35f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 59.56f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 59.96f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 60.23f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 60.57f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 60.79f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 61.15f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 61.50f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 61.75f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 62.08f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 62.39f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 62.76f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 63.02f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 63.25f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 63.67f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 64.15f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 64.61f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 64.94f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 65.25f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 65.79f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 66.48f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 66.81f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 67.56f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 68.27f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 68.94f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 69.57f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 70.22f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 70.83f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 71.47f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 74.27f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 76.22f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 76.44f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 76.69f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 76.95f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 77.23f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 77.46f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 77.71f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 78.08f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 78.37f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 78.63f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 78.91f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 79.97f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 81.20f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 81.44f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 81.69f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 81.96f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 82.22f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 82.53f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 82.79f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 83.04f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 83.34f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 84.24f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 84.54f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 84.79f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 85.08f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 85.80f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 86.22f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 86.43f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 86.67f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 87.04f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 87.35f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 87.63f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 88.10f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 88.40f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 88.74f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 89.03f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 89.96f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 91.24f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 91.46f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 91.75f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 92.02f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 92.37f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 92.68f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 92.97f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 93.30f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 93.63f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 94.36f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 94.65f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 94.96f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 95.28f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 95.83f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 96.42f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 97.06f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 97.71f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 98.33f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 109.03f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 109.59f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 110.21f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 110.83f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 111.46f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 112.11f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 112.87f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 113.35f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 113.97f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 114.24f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 114.48f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 114.75f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 115.06f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 115.33f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 115.63f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 115.84f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 116.20f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 116.53f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 116.77f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 117.01f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 117.46f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 117.70f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 118.11f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 118.37f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 119.05f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 119.48f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 119.77f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 120.04f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 120.31f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 120.63f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 120.88f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 121.25f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 121.55f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 121.81f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 122.09f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 122.40f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 122.73f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 123.06f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 123.43f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 124.09f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 124.34f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 124.60f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 124.95f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 125.20f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 125.60f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 125.84f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 126.39f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 126.65f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 126.93f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 127.21f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 127.44f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 127.77f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 128.06f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 128.31f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 129.52f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 129.94f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 130.20f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 130.57f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 130.90f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 131.18f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 131.50f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 131.78f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 132.08f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 132.33f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 132.71f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 133.05f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 133.37f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 133.70f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 134.04f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 136.48f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 138.72f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 138.93f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 139.16f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 139.46f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 139.71f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 139.94f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 140.18f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 140.61f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 140.85f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 141.13f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 141.38f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 142.46f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 143.72f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 143.96f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 144.21f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 144.51f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 144.82f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 145.13f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 145.35f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 145.62f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 145.87f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 146.77f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 147.06f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 147.29f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 147.50f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 148.29f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 148.74f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 148.92f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 149.16f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 149.46f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 149.66f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 149.98f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 150.21f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 150.58f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 150.85f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 151.09f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 151.38f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 152.47f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 153.68f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 153.90f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 154.15f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 154.48f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 154.72f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 154.98f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 155.23f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 155.53f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 155.79f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 156.07f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 156.79f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 157.04f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 157.41f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 157.78f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 158.32f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 158.90f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 159.49f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 160.15f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 160.76f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 161.55f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 162.10f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 162.34f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 162.61f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 162.98f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 163.24f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 163.52f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 163.73f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 164.04f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 164.31f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 164.61f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 164.92f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 165.17f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 165.60f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 165.84f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 166.22f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 166.64f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 166.92f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 167.22f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 167.60f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 167.98f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 168.18f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 168.45f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 168.77f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 169.05f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 169.28f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 169.56f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 169.78f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 170.06f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 170.57f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 170.82f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 171.17f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 171.56f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 171.86f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 172.14f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 172.47f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 172.74f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 173.13f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 173.49f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 173.76f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 174.12f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 174.33f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 174.62f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 174.92f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 175.14f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 175.66f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 175.94f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 176.20f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 176.55f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 176.83f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 177.10f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 177.54f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 177.73f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 178.12f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 178.37f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 178.67f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 179.03f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 179.30f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 179.59f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 179.87f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 180.14f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 180.48f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 180.84f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 181.11f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 181.80f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 182.05f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 182.32f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 182.66f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 183.27f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 183.89f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 184.49f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 185.13f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 185.78f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 186.43f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 189.35f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 191.30f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 191.51f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 191.75f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 192.03f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 192.29f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 192.56f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 192.76f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 193.07f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 193.33f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 193.60f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 193.83f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 194.88f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 196.19f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 196.43f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 196.65f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 196.90f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 197.13f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 197.43f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 197.70f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 197.97f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 198.31f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 199.25f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 199.49f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 199.70f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 199.91f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 200.76f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 201.26f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 201.49f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 201.87f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 202.15f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 202.43f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 202.65f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 203.05f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 203.33f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 203.62f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 203.88f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 204.85f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 206.26f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 206.49f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 206.78f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 207.06f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 207.36f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 207.62f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 207.86f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 208.14f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 208.37f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 208.68f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 209.28f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 209.56f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 209.93f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 210.27f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 210.84f));
            arrowList.Add(new Arrows(upArrowPos, 768, false, 211.42f));
            arrowList.Add(new Arrows(rightArrowPos, 768, false, 212.09f));
            arrowList.Add(new Arrows(downArrowPos, 768, false, 212.74f));
            arrowList.Add(new Arrows(leftArrowPos, 768, false, 213.30f));

            player1 = new Player(initialPlayerPosition, initialPlayerPosition);
            stopwatch.Start();
        }

        public void EndLevel()
        {
            if (stopwatch.Elapsed.TotalSeconds >= endLevelTime)
            {
                stopwatch.Restart();
                InitializeLevel();

                if (GameManager.Instance.Points.RythmPoints >= gamePointsToWin)
                {
                    GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                    GameManager.Instance.ChangeStage(GameStage.win);
                }else
                {
                    GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                    GameManager.Instance.ChangeStage(GameStage.lose);
                }
            }
        }

        public void Update()
        {
            player1.Update();

            for (int i = 0; i < arrowList.Count; i++)
            {
                arrowList[i].Update();
            }

            EndLevel();
        }
        public void Render()
        {
            Engine.Clear();
            Engine.Draw(background, 0, 0);
            player1.Render();

            for (int i = 0; i < arrowList.Count; i++)
            {
                arrowList[i].Render();
            }

            Engine.Show();
        }
    }
}
