using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyGame
{
    public class LevelController
    {
        private static Stopwatch stopwatch = new Stopwatch();
        private List<Arrows> arrowList = new List<Arrows>();
        private Image background1 = Engine.LoadImage("assets/Background.jpg");
        private Image background2 = Engine.LoadImage("assets/Background2.jpg");
        private Player player1;
        private GetReadySign getReadySign;
        private int endLevel1Time = 228;
        private int endLevel2Time = 216;
        private int gamePointsToWin1 = 3050;
        private int gamePointsToWin2 = 2770;
        private int initialPlayerPosition = 300;
        private ArrowsFactory arrowsFactory = new ArrowsFactory();
        private HUD hud = new HUD();
        private TriggerArrowAnimation triggerArrowAnimation = new TriggerArrowAnimation();
        private int level;


        public List<Arrows> ArrowList => arrowList;
        public Stopwatch Stopwatch => stopwatch;
        public Player Player1 => player1;
        public TriggerArrowAnimation TriggerArrowAnimation => triggerArrowAnimation;

        public void InitializeLevel(int level)
        {
            this.level = level;
            if (level == 1)
            {
                arrowList.Add(ArrowsFactory.CreateArrows(ArrowType.rightArrowS, 0f));
                arrowList.Add(ArrowsFactory.CreateArrows(ArrowType.upArrowS, 0f));
                arrowList.Add(ArrowsFactory.CreateArrows(ArrowType.downArrowS, 0f));
                arrowList.Add(ArrowsFactory.CreateArrows(ArrowType.leftArrowS, 0f));
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 18.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 19.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 19.95f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 20.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 20.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 20.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 21.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 21.60f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 21.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 22.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 22.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 22.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 23.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 23.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 23.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 24.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 24.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 24.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 25.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 25.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 25.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 26.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 26.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 26.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 27.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 27.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 27.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 28.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 28.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 28.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 29.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 29.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 29.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 30.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 30.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 30.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 30.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 31.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 31.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 31.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 32.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 32.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 32.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 33.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 33.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 33.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 34.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 34.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 34.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 34.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 35.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 35.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 36.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 36.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 36.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 37.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 37.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 37.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 38.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 38.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 38.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 39.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 39.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 39.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 39.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 40.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 40.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 40.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 41.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 41.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 41.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 41.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 42.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 42.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 42.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 43.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 43.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 43.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 46.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 48.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 49.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 49.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 49.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 49.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 50.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 50.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 50.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 51.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 51.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 51.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 51.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 52.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 52.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 52.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 52.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 53.21f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 53.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 53.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 54.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 54.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 54.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 54.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 55.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 55.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 55.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 56.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 56.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 56.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 56.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 57.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 57.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 58.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 58.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 58.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 58.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 59.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 59.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 59.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 60.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 60.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 60.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 61.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 61.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 61.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 61.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 62.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 62.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 62.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 63.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 63.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 63.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 64.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 64.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 64.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 65.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 65.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 65.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 65.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 66.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 66.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 66.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 67.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 67.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 68.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 68.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 69.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 69.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 69.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 70.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 70.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 70.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 71.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 71.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 71.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 71.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 72.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 72.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 72.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 73.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 73.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 73.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 76.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 78.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 78.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 79.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 79.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 79.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 79.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 80.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 80.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 80.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 81.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 82.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 83.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 83.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 84.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 84.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 84.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 85.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 85.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 85.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 86.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 86.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 87.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 87.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 88.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 88.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 88.73f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 88.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 89.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 89.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 89.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 90.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 90.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 91.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 91.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 92.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 93.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 93.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 94.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 94.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 94.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 95.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 95.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 95.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 95.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 96.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 96.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 97.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 97.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 98.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 98.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 99.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 100.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 100.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 101.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 111.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 111.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 111.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 112.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 112.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 112.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 113.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 113.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 113.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 114.21f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 114.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 114.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 114.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 115.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 115.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 115.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 116.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 116.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 116.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 117.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 117.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 117.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 118.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 118.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 118.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 118.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 119.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 119.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 119.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 120.02f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 120.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 120.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 121.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 121.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 122.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 122.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 122.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 122.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 123.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 123.60f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 123.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 124.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 124.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 124.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 125.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 125.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 125.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 126.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 126.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 126.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 127.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 127.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 127.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 127.95f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 128.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 128.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 128.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 129.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 129.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 129.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 130.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 130.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 130.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 131.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 131.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 132.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 133.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 133.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 134.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 134.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 135.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 136.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 139.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 141.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 141.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 141.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 141.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 142.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 142.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 142.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 142.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 143.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 143.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 143.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 143.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 144.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 145.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 146.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 146.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 146.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 147.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 147.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 147.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 147.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 148.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 149.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 149.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 149.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 149.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 150.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 151.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 151.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 151.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 151.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 152.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 152.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 152.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 153.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 153.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 153.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 153.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 154.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 156.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 156.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 156.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 156.95f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 157.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 157.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 157.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 158.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 158.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 159.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 159.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 159.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 160.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 160.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 161.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 161.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 162.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 163.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 164.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 164.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 164.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 165.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 165.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 165.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 165.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 166.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 166.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 166.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 166.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 167.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 167.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 167.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 167.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 168.21f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 168.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 168.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 169.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 169.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 169.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 169.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 170.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 170.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 171.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 171.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 171.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 171.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 172.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 172.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 172.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 173.21f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 173.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 173.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 174.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 174.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 174.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 175.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 175.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 176.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 176.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 176.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 176.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 177.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 177.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 177.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 178.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 178.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 178.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 179.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 179.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 179.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 179.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 180.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 180.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 180.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 181.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 181.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 181.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 182.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 182.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 182.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 183.02f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 183.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 183.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 184.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 184.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 184.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 185.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 185.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 185.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 185.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 186.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 186.73f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 186.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 187.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 187.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 187.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 188.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 188.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 188.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 191.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 193.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 193.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 193.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 194.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 194.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 194.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 195.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 195.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 195.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 196.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 197.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 198.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 198.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 199.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 199.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 199.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 199.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 200.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 200.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 200.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 201.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 201.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 202.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 202.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 203.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 203.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 203.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 204.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 204.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 204.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 204.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 205.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 205.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 206.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 206.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 207.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 208.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 208.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 209.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 209.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 209.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 209.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 210.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 210.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 210.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 211.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 211.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 211.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 212.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 212.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 213.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 213.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 214.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 214.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 215.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 216.35f);

                player1 = new Player(initialPlayerPosition, initialPlayerPosition);
                getReadySign = new GetReadySign();
                stopwatch.Start();
            }
            if (level == 2)
            {
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 6.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 6.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 15.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 16.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 16.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 16.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 16.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 17.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 17.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 17.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 17.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 17.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 18.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 18.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 18.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 19.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 19.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 19.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 19.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 20.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 20.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 20.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 21.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 21.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 21.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 21.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 22.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 22.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 23.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 23.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 23.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 23.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 24.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 24.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 25.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 25.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 25.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 26.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 26.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 26.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 27.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 27.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 27.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 27.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 28.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 28.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 28.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 29.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 29.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 29.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 30.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 30.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 30.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 30.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 31.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 31.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 31.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 32.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 32.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 32.88f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 33.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 33.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 33.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 34.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 34.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 34.95f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 35.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 35.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 35.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 36.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 36.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 36.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 37.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 37.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 37.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 37.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 38.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 38.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 38.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 39.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 39.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 39.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 40.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 40.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 40.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 41.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 41.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 41.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 42.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 42.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 42.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 44.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 44.73f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 45.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 45.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 46.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 47.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 47.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 47.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 49.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 49.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 49.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 50.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 50.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 51.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 51.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 51.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 51.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 51.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 52.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 52.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 52.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 53.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 53.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 53.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 53.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 54.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 54.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 55.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 56.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 56.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 56.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 57.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 58.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 58.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 59.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 59.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 60.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 60.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 60.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 60.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 61.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 61.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 61.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 61.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 62.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 62.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 62.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 63.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 63.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 63.95f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 64.21f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 64.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 64.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 65.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 65.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 65.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 65.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 66.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 66.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 66.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 66.83f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 67.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 67.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 67.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 68.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 68.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 68.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 69.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 69.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 69.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 70.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 70.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 70.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 70.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 71.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 71.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 71.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 71.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 72.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 72.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 73.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 73.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 73.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 73.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 74.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 74.59f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 74.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 75.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 75.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 75.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 76.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 76.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 76.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 77.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 77.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 77.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 78.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 78.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 78.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 78.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 79.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 79.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 79.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 80.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 80.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 80.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 81.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 81.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 86.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 86.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 86.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 87.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 87.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 87.60f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 87.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 88.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 88.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 88.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 88.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 89.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 89.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 89.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 90.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 90.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 90.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 90.81f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 91.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 91.37f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 91.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 91.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 92.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 92.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 92.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 93.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 93.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 94.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 94.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 94.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 94.88f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 95.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 95.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 96.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 96.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 96.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 97.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 97.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 97.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 97.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 98.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 98.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 98.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 99.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 99.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 99.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 100.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 100.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 100.60f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 101.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 101.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 101.64f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 101.91f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 102.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 102.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 103.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 103.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 103.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 103.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 104.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 104.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 105.31f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 105.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 105.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 106.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 106.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 106.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 106.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 107.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 107.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 107.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 108.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 108.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 108.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 108.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 109.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 109.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 109.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 110.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 110.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 110.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 110.96f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 111.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 111.69f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 112.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 112.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 112.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 113.13f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 113.36f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 114.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 115.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 115.58f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 115.88f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 116.29f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 117.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 117.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 118.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 118.51f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 119.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 119.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 120.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 120.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 121.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 121.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 121.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 122.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 122.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 122.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 122.89f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 123.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 123.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 123.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 124.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 124.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 124.77f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 125.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 125.55f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 126.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 127.12f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 127.50f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 127.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 129.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 129.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 129.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 130.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 130.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 131.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 131.47f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 131.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 131.92f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 132.16f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 132.41f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 132.73f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 132.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 133.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 133.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 152.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 153.02f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 153.26f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 153.49f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 153.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 154.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 154.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 154.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 154.75f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 155.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 155.28f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 155.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 155.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 156.03f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 156.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 156.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 156.78f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 157.07f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 157.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 157.57f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 157.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 158.04f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 158.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 158.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 158.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 159.05f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 159.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 159.95f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 160.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 160.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 160.82f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 161.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 161.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 161.99f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 162.18f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 162.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 162.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 163.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 163.39f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 163.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 163.86f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 164.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 164.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 164.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 165.19f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 165.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 165.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 166.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 166.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 167.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 167.43f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 167.71f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 167.94f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 168.24f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 168.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 169.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 169.32f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 169.63f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 169.87f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 170.14f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 170.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 170.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 173.80f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 174.08f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 174.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 174.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 176.10f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 176.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 176.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 177.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 178.42f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 178.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 179.20f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 179.66f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 180.27f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 180.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 180.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 180.97f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 181.21f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 181.45f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 181.68f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 181.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 182.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 182.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 182.70f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 182.98f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 183.46f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 183.72f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 184.00f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 184.44f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 185.53f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 185.93f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 186.34f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 186.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 187.85f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 188.22f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 188.62f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 189.06f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 189.65f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 189.90f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 190.15f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 190.33f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 190.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 190.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 191.11f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 191.30f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 191.56f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 191.84f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 192.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 192.40f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 194.76f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 199.09f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 199.38f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 199.54f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 199.79f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 200.17f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 200.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 200.74f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 201.01f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 201.23f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 201.61f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 201.88f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 204.48f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 205.25f);
                arrowsFactory.AddArrowToQueue(ArrowType.rightArrow, 206.35f);
                arrowsFactory.AddArrowToQueue(ArrowType.leftArrow, 207.52f);
                arrowsFactory.AddArrowToQueue(ArrowType.upArrow, 208.67f);
                arrowsFactory.AddArrowToQueue(ArrowType.downArrow, 209.79f);
                stopwatch.Start();
            }
        }

        public void EndLevel()
        {
            if (level == 1)
            {
                if (stopwatch.Elapsed.TotalSeconds >= endLevel1Time)
                {
                    stopwatch.Restart();
                    stopwatch.Stop();

                    if (GameManager.Instance.Points.RythmPoints >= gamePointsToWin1)
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.nextLevel);
                    }
                    else
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.lose);
                    }
                }
            }
            if (level == 1)
            {
                if (stopwatch.Elapsed.TotalSeconds >= endLevel1Time)
                {
                    stopwatch.Restart();
                    stopwatch.Stop();

                    if (GameManager.Instance.Points.RythmPoints >= gamePointsToWin1)
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.win);
                    }
                    else
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.lose);
                    }
                }
            }
            if (level == 2)
            {
                if (stopwatch.Elapsed.TotalSeconds >= endLevel2Time)
                {
                    stopwatch.Restart();
                    stopwatch.Stop();

                    if (GameManager.Instance.Points.RythmPoints >= gamePointsToWin2)
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.win);
                    }
                    else
                    {
                        GameManager.Instance.Points.RythmPoints = -GameManager.Instance.Points.RythmPoints;
                        GameManager.Instance.ChangeStage(GameStage.lose);
                    }
                }
            }
        }

        public enum ArrowDirection
        {
            Left,
            Right,
            Up,
            Down
        }

        public void Update()
        {
            player1.Update();
            getReadySign.Update();
            arrowsFactory.Update();

            for (int i = 0; i < arrowList.Count; i++)
            {
                arrowList[i].Update();
            }

            EndLevel();
        }
        public void Render()
        {
            Engine.Clear();
            if (level == 1)
            {
                Engine.Draw(background1, 0, 0);
            }
            if (level == 2)
            {
                Engine.Draw(background2, 0, 0);
            }
            player1.Render();
            getReadySign.Render();
            hud.Render();

            for (int i = 0; i < arrowList.Count; i++)
            {
                arrowList[i].Render();
            }

            Engine.Show();
        }
    }
}
